---
title: "Ramen"
author: "Randall Madsen"
date: "June 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plotly)

ramen_ratings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-04/ramen_ratings.csv")

ramen_ratings %>% 
  filter(stars >= 4) %>% 
  group_by(country, brand) %>% 
  count(country, sort = T) %>% 
  top_n(25, country)



board_games %>%
  inner_join(categorical_variables, by = c("game_id", "name")) %>%
  filter(type == "family") %>%
  mutate(value = fct_lump(value, 15),
         value = fct_reorder(value, average_rating)) %>%
  ggplot(aes(value, average_rating)) +
  geom_boxplot() +
  coord_flip()

ramen_ratings %>% 
  filter(!is.na(style), style == c("Cup", "Pack", "Bowl", "Box", "Tray")) %>% 
  # mutate(style = fct_reorder(style)) %>% 
  ggplot(aes(style, stars)) +
  geom_boxplot() +
  coord_flip()


ramen_ratings %>% 
  # filter(stars >= 4) %>% 
  group_by(style, country) %>% 
  count(style, sort = T) %>% 
  ungroup() %>% 
  mutate(country = fct_lump(country, 3),
         style = fct_inorder(style)) %>% 
  filter(country != "Other", !is.na(style)) %>% 
  ggplot(aes(style, n, fill = country)) +
  geom_col() +
  scale_y_continuous() +
  expand_limits(y = 0) +
  scale_fill_manual(values=c("#FFDE00", "#000097", "#B22234")) +
  facet_wrap(~ country, scales = "free_y")
```

